- name: INSTALLATION OF NGINX
  hosts: frontend
  become: yes
  tasks:
    - name: nginxx
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: nginx2
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
