- name: Variable declarations
  hosts: local
  connection: local
  vars:
    NAME: SATYOLOGY
    AGE: 20
  tasks:
    - name: Writing variables
      ansible.builtin.debug:
        msg: "MY name is {{ NAME }} and my age is {{ AGE }}"

    - name: Writing variables
      ansible.builtin.debug:
        msg: "MY name is {{ NAME }} and my age is {{ AGE }}"
