# args .. variable command : ansible-playbook -i inventory.ini 6sixth.yaml -e "NAME=SATYAVARDHAN AGE=92"
- name: FROM ARGUMENTS
  hosts: local
  connection: local
  tasks:
    - name: NEW VARIABLE
      ansible.builtin.debug:
        msg: "MY name is {{ NAME }} and age is {{ AGE }}"
